name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.18.0
homepage: https://github.com/maplibre/flutter-maplibre-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapLibreMapPlugin
        fileName: maplibre_gl_web.dart

dependencies:
  js: ^0.6.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/ManoyloK/flutter-maplibre-gl.git
      ref: update-gradle-dependencies
      path: maplibre_gl_platform_interface
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
